### PR TITLE
fixed bug wrt strand specific simulation

### PR DESCRIPTION
**Pull request by mikelove**

### CODE REVIEW

**Comment by alyssafrazee** [comment]
Thanks for doing this!

**Comment by alyssafrazee** [comment]
@JMF47 can you get this into Bioc?

**Comment by mikelove** [comment]
Thank you @alyssafrazee and @JMF47 !

**Comment by mikelove** [comment]
hi @JMF47 & @jtleek 

Use of the stranded option in the Bioc devel branch is of interest in the research community:

https://twitter.com/BenLangmead/status/765610911008567296

However, the Bioc devel branch still contains the bug which was fixed in this commit. Let me know if I can help at all.

**Comment by JMF47** [comment]
Hey Mike, thanks for the heads up. I thought I had pushed it all the way to bioC but it might have stalled at some point. Let me do it when I get home today

On Aug 17, 2016, at 9:19 AM, Mike Love <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @JMF47<https://github.com/JMF47> & @jtleek<https://github.com/jtleek>

Use of the stranded option in the Bioc devel branch is of interest in the research community:

https://twitter.com/BenLangmead/status/765610911008567296

However, the Bioc devel branch still contains the bug which was fixed in this commit. Let me know if I can help at all.

-

**Comment by jtleek** [comment]
Hi everyone

I've been meaning to get all the new "bridges" set up for all leekgroup
packages. But it is a bit of a pain so I keep pushing it off. I'll try to
prioritize as well

Jeff

**Pull request merged**
