### PR TITLE
Stranded RNA-Seq

### PR DESCRIPTION
**Pull request by jwcasement**
Hello Alyssa,

I've added aditional parameters to the simulate_experiment function to enable stranded RNA-seq data to be simulated. The default option is for unstranded data (as before); additional strand-specific protocol options are 'firststrand' and 'secondstrand'.

I've also included the option to set an error rate for strandedness should this be required (default value zero).

Best regards,

John.

### CODE REVIEW

**Comment by alyssafrazee** [comment]
I'm so sorry for the delay. The past couple months got a bit hectic and development stopped for a while, and then I had to do a major reorg of the package. Wanted to let you know that I haven't forgotten about this and will review the stranded options as soon as I can.

**Comment by lpantano** [comment]
Hi,

any chance this will go on?  i think is a very good improvement.

nice work!

**Comment by alyssafrazee** [comment]
Would love to have this as a feature. I can't auto-merge the PR so will need to take time to review it, and will get to it as soon as I can. Thanks again for your patience!

**Comment by alyssafrazee** [comment]
Strand-specific option was added in https://github.com/alyssafrazee/polyester/pull/33 -- I hope that one added the needed functionality (and was able to merge that one without conflict). Closing this in favor of that, but feel free to reopen if it doesn't solve the problem.

**Pull request closed without merging**
